// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace RetencaoDeRencimentos.Cenario03
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Realizar o repasse de um valor parametrizado para um credenciado por meio de dois" +
        " pagamentos")]
    public partial class RealizarORepasseDeUmValorParametrizadoParaUmCredenciadoPorMeioDeDoisPagamentosFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "cenario03.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Realizar o repasse de um valor parametrizado para um credenciado por meio de dois" +
                    " pagamentos", "  EU, como responsável pelo pagamento da rede credenciada\r\n  QUERO poder realizar" +
                    " a retenção de rendimentos de prestadores\r\n  PARA atender a determinação judicia" +
                    "l de pensão alimentícia", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Prestador Credenciado com dois pagamentos na competência onde o primeiro não atin" +
            "ge o valor total do benefício")]
        [NUnit.Framework.CategoryAttribute("FLUXO_PRINCIPAL")]
        public virtual void PrestadorCredenciadoComDoisPagamentosNaCompetenciaOndeOPrimeiroNaoAtingeOValorTotalDoBeneficio()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Prestador Credenciado com dois pagamentos na competência onde o primeiro não atin" +
                    "ge o valor total do benefício", new string[] {
                        "FLUXO_PRINCIPAL"});
#line 8
    this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "RepassePensaoAlimenticia"});
            table1.AddRow(new string[] {
                        "01",
                        "2.500,00"});
#line 9
    testRunner.Given("um prestador credenciado que deve pagar pensão alimentícia", ((string)(null)), table1, "Dado ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "ValorApresentado",
                        "ValorGlosado",
                        "ValorAPagar",
                        "DescontoDeINSS",
                        "DescontoDeIRRF",
                        "ValorLiquido"});
            table2.AddRow(new string[] {
                        "01",
                        "3.250,00",
                        "750,00",
                        "2.500,00",
                        "204,85",
                        "273,73",
                        "2.021,42"});
#line 12
    testRunner.When("um PEG for faturado", ((string)(null)), table2, "Quando ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "RepasseDaPensaoAlimenticia",
                        "ValorLiquido"});
            table3.AddRow(new string[] {
                        "01",
                        "2.500,00",
                        "0,00"});
#line 15
    testRunner.Then("restará ainda um valor para quitação", ((string)(null)), table3, "Então ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "ValorApresentado",
                        "ValorGlosado",
                        "ValorAPagar",
                        "DescontoDeINSS",
                        "DescontoDeIRRF",
                        "ValorLiquido"});
            table4.AddRow(new string[] {
                        "01",
                        "1.250,00",
                        "0,00",
                        "1.250,00",
                        "102,42",
                        "136,86",
                        "1.010,72"});
#line 18
    testRunner.And("quando for realizado o faturamento de um segundo PEG", ((string)(null)), table4, "E ");
#line 21
    testRunner.And("deverá gerar um desconto referente a pensão alimentícia ainda não quitado no mês", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "RepasseDaPensaoAlimenticia",
                        "ValorLiquido"});
            table5.AddRow(new string[] {
                        "01",
                        "478,58",
                        "532,14"});
#line 22
    testRunner.And("um valor líquido de pagamento", ((string)(null)), table5, "E ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion

