// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ConsultaFaturasEmAberto.Cenario01
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Beneficiário ativo com uma fatura em aberto")]
    public partial class BeneficiarioAtivoComUmaFaturaEmAbertoFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "BeneficiarioAtivoComUmaFaturaEmAberto.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Beneficiário ativo com uma fatura em aberto", "EU como responsável pela análise de crédito para empréstimos\r\nQUERO saber o saldo" +
                    " devedor do titular \r\nPARA consultar de faturas em aberto", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Consultar o saldo devedor de um beneficiário com apenas uma fatura em aberto.")]
        [NUnit.Framework.CategoryAttribute("FLUXO_PRINCIPAL")]
        public virtual void ConsultarOSaldoDevedorDeUmBeneficiarioComApenasUmaFaturaEmAberto_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Consultar o saldo devedor de um beneficiário com apenas uma fatura em aberto.", new string[] {
                        "FLUXO_PRINCIPAL"});
#line 8
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "MatriculaFuncional",
                        "Nome",
                        "Cpf",
                        "Modulos",
                        "Plano"});
            table1.AddRow(new string[] {
                        "1",
                        "00123456",
                        "\"JOAO DA SILVA\"",
                        "\"79956013013\"",
                        "\"1 - MSI - METRUS SAUDE INTEGRAL\"",
                        "\"1 – Metro\""});
#line 9
testRunner.Given("um beneficiário titular com apenas uma fatura em aberto", ((string)(null)), table1, "Dado ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "CodigoDoPlano",
                        "MatriculaFuncional",
                        "Cpf",
                        "DataReferencia"});
            table2.AddRow(new string[] {
                        "1",
                        "1",
                        "\"00123456\"",
                        "\"79956013013\"",
                        "\"2019-02-25\""});
            table2.AddRow(new string[] {
                        "2",
                        "1",
                        "null",
                        "\"79956013013\"",
                        "\"2019-02-25\""});
            table2.AddRow(new string[] {
                        "3",
                        "1",
                        "\"00123456\"",
                        "null",
                        "\"2019-02-25\""});
#line 12
testRunner.When("for consultado o saldo devedor", ((string)(null)), table2, "Quando ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "CodigoDoPlano",
                        "MatriculaFuncional",
                        "Nome",
                        "Saldo",
                        "Juros",
                        "Multa",
                        "Correcao",
                        "Total",
                        "Faturas"});
            table3.AddRow(new string[] {
                        "1",
                        "1",
                        "\"00123456\"",
                        "\"JOAO DA SILVA\"",
                        "123.45",
                        "1.5",
                        "10.05",
                        "22.35",
                        "157.35",
                        "[]"});
#line 17
testRunner.Then("o serviço deverá retornar", ((string)(null)), table3, "Então ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "IdFaturas",
                        "NumeroFatura",
                        "Parcela",
                        "Vencimento",
                        "Saldo",
                        "Juros",
                        "Multa",
                        "Correcao",
                        "Total",
                        "Modulos"});
            table4.AddRow(new string[] {
                        "1",
                        "98765",
                        "25",
                        "\"2019-01-25\"",
                        "123.45",
                        "1.5",
                        "10.05",
                        "22.35",
                        "157.35",
                        "[]"});
#line 20
testRunner.And("a Fatura", ((string)(null)), table4, "E ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "IdModulos",
                        "DescricaoModulo",
                        "Tipo",
                        "Competencia",
                        "NomeBeneficiario"});
            table5.AddRow(new string[] {
                        "1",
                        "\"1 - MSI - METRUS SAUDE INTEGRAL\"",
                        "\"Mensalidade\"",
                        "\"2019-01-01\"",
                        "\"JOAO DA SILVA\""});
            table5.AddRow(new string[] {
                        "1",
                        "\"1 - MSI - METRUS SAUDE INTEGRAL\"",
                        "\"Mensalidade\"",
                        "\"2019-01-01\"",
                        "\"MARIA DA SILVA\""});
#line 23
testRunner.And("os Modulos desta fatura", ((string)(null)), table5, "E ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion

