// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ConsultaFaturasEmAberto.Cenario04
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Beneficiario ativo com dados diferentes do sistema")]
    public partial class BeneficiarioAtivoComDadosDiferentesDoSistemaFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "BeneficiarioAtivoComDadosDiferentesDoSistema.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Beneficiario ativo com dados diferentes do sistema", "EU como responsável pela análise de crédito para empréstimos\r\nQUERO saber o saldo" +
                    " devedor do titular \r\nPARA consultar de faturas em aberto", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Consultar o saldo devedor de um beneficiário informando matrícula funcional e cpf" +
            " diferentes dos cadastrados no sistema")]
        [NUnit.Framework.CategoryAttribute("FLUXO_ALTERNATIVO")]
        public virtual void ConsultarOSaldoDevedorDeUmBeneficiarioInformandoMatriculaFuncionalECpfDiferentesDosCadastradosNoSistema()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Consultar o saldo devedor de um beneficiário informando matrícula funcional e cpf" +
                    " diferentes dos cadastrados no sistema", new string[] {
                        "FLUXO_ALTERNATIVO"});
#line 8
this.ScenarioSetup(scenarioInfo);
#line 9
testRunner.Given("um beneficiário titular", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "MatriculaFuncional",
                        "Nome",
                        "Cpf",
                        "Modulos",
                        "Plano"});
            table1.AddRow(new string[] {
                        "1",
                        "00123456",
                        "\"JOAO DA SILVA\"",
                        "\"79956013013\"",
                        "\"1 - MSI - METRUS SAUDE INTEGRAL\"",
                        "\"1 – Metro\""});
#line 10
testRunner.And("uma fatura em aberto", ((string)(null)), table1, "E ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "CodigoDoPlano",
                        "MatriculaFuncional",
                        "Cpf",
                        "DataReferencia"});
            table2.AddRow(new string[] {
                        "1",
                        "1",
                        "\"123321\"",
                        "\"14458764235\"",
                        "\"2019-02-25\""});
#line 13
testRunner.When("for consultado", ((string)(null)), table2, "Quando ");
#line 16
testRunner.Then("o serviço deverá retornar uma mensagem de erro", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion

