/ ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace 01PensaoAlimenticia.Cenario01
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Realizar o repasse de um valor parametrizado para um credenciado com um único pag" +
        "amento no mês")]
    public partial class RealizarORepasseDeUmValorParametrizadoParaUmCredenciadoComUmUnicoPagamentoNoMesFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "pensaoComUnicoPagamentoNoMes.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Realizar o repasse de um valor parametrizado para um credenciado com um único pag" +
                    "amento no mês", "EU, como responsável pelo pagamento da rede credenciada\r\nQUERO poder realizar a r" +
                    "etenção de rendimentos de prestadores\r\nPARA atender a determinação judicial de p" +
                    "ensão alimentícia", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Credenciado com um único pagameto no mês")]
        [NUnit.Framework.CategoryAttribute("FLUXO_PRINCIPAL")]
        public virtual void CredenciadoComUmUnicoPagametoNoMes()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Credenciado com um único pagameto no mês", new string[] {
                        "FLUXO_PRINCIPAL"});
#line 8
 this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "RepasseDaPensaoAlimenticia"});
            table1.AddRow(new string[] {
                        "01",
                        "1.800,00"});
#line 9
 testRunner.Given("um credenciado que deve pagar um valor mensal de pensão alimentícia", ((string)(null)), table1, "Dado ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "ValorApresentado",
                        "ValorGlosado",
                        "ValorAPagar",
                        "DescontoDeINSS",
                        "DescontoDeIRRF",
                        "ValorLiquido"});
            table2.AddRow(new string[] {
                        "01",
                        "7.000,00",
                        "200,00",
                        "6.800,00",
                        "621,04",
                        "829,86",
                        "5.349,10"});
#line 12
 testRunner.When("for realizado o faturamento do pagamento de um PEG", ((string)(null)), table2, "Quando ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "RepasseDaPensaoAlimenticia",
                        "ValorLiquido"});
            table3.AddRow(new string[] {
                        "01",
                        "1.800,00",
                        "3.549,10"});
#line 15
 testRunner.Then("deverá ser gerado o repasse referente a pensão alimentícia, gerando para o creden" +
                    "ciado o valor líquido de R$ 3.549,10.", ((string)(null)), table3, "Então ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion

