// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
using System;

namespace NUnit
{
    internal class Framework
    {
        internal class TestFixtureAttribute : Attribute
        {
        }

        internal class DescriptionAttribute : Attribute
        {
        }
    }
}